### ISSUE TITLE
Odd container behavior

### ISSUE THREAD

**Issue by scaleoutsean** [mjavier2k/solidfire-exporter#45]
It's been a long day so maybe I made a mistake here but:

```
$ cat .env_file 
SOLIDFIRE_LISTEN_ADDRESS="0.0.0.0:9987"
SOLIDFIRE_CLIENT_ENDPOINT="https://192.168.1.30/json-rpc/11.3"
SOLIDFIRE_CLIENT_USERNAME="admin"
SOLIDFIRE_CLIENT_PASSWORD="admin"
SOLIDFIRE_CLIENT_INSECURE=true
SOLIDFIRE_CLIENT_TIMEOUT=30
```

With `:latest`, container comes up but crashes the moment I access it in the browser (192.x.x.x:9987 or 127.0.0.1:9987):

```
$ docker run --env-file=.env_file --rm -p 9987:9987 mjavier/solidfire-exporter:latest
Wed Mar 10 11:36:22  [INFO ] No config file found.
Wed Mar 10 11:36:22  [INFO ] Version: 
Wed Mar 10 11:36:22  [INFO ] Built: 
Wed Mar 10 11:36:22  [INFO ] initializing new solidfire collector
Wed Mar 10 11:36:22  [INFO ] initializing new solidfire client
Wed Mar 10 11:36:22  [WARN ] TLS certificate verification is currently disabled - This is not recommended.
Wed Mar 10 11:36:22  [INFO ] RPC Server: "https://192.168.1.30/json-rpc/11.3"
Wed Mar 10 11:36:22  [INFO ] Config setting found for config: config.yaml
Wed Mar 10 11:36:22  [INFO ] Config setting found for listen.address: 0.0.0.0:9987
Wed Mar 10 11:36:22  [INFO ] Config setting found for client.endpoint: "https://192.168.1.30/json-rpc/11.3"
Wed Mar 10 11:36:22  [INFO ] Config setting found for client.timeout: 30
Wed Mar 10 11:36:22  [INFO ] Booted and listening on 0.0.0.0:9987/metrics
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6b94b7]

goroutine 23 [running]:
net/http.(*Request).SetBasicAuth(0x0, 0xc00002801a, 0x7, 0xc00002804a, 0x7)
	/usr/local/go/src/net/http/request.go:960 +0x37
github.com/mjavier2k/solidfire-exporter/pkg/solidfire.doRpcCall(0xc0000b6cc0, 0xc0001167d0, 0x47, 0x50, 0x0, 0x0, 0x0, 0x0, 0x0)
	/src/pkg/solidfire/solidfire.go:42 +0x143
github.com/mjavier2k/solidfire-exporter/pkg/solidfire.(*Client).ListVolumes(0xc0000b6cc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/src/pkg/solidfire/solidfire.go:72 +0x163
github.com/mjavier2k/solidfire-exporter/pkg/prom.(*solidfireCollector).Collect(0xc0000b2138, 0xc00013e0c0)
	/src/pkg/prom/collector.go:172 +0x5c
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.4.1/prometheus/registry.go:443 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.4.1/prometheus/registry.go:535 +0xe12
```

With `v0.5.1`, container doesn't crash, but also does not work (empty metrics page). Additionally it's making requests to 192.168.1.2 which doesn't seem related to my setup.

```
docker run --env-file=.env_file --rm -p 9987:9987 mjavier/solidfire-exporter:v0.5.1
Unable to find image 'mjavier/solidfire-exporter:v0.5.1' locally
v0.5.1: Pulling from mjavier/solidfire-exporter
df20fa9351a1: Already exists 
7758c09ac8cd: Pull complete 
377dec8c23f2: Pull complete 
e54644b27f5b: Pull complete 
Digest: sha256:3d4adc489e520ea88399f3dd46752a4c88abba1e24ab500f190b30c6d17b9f3d
Status: Downloaded newer image for mjavier/solidfire-exporter:v0.5.1
Wed Mar 10 11:37:30  [INFO ] Version: 
Wed Mar 10 11:37:30  [INFO ] Built: 
Wed Mar 10 11:37:30  [INFO ] initializing new solidfire collector
Wed Mar 10 11:37:30  [INFO ] initializing new solidfire client
Wed Mar 10 11:37:30  [INFO ] RPC Server: https://192.168.1.2/json-rpc/11.3
Wed Mar 10 11:37:30  [INFO ] Booted and listening on 0.0.0.0:9987/metrics
Wed Mar 10 11:38:00  [ERROR] Error making RPC call {"method":"ListVolumes","params":{"includeVirtualVolumes":true},"id":1}: Post https://192.168.1.2/json-rpc/11.3: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Wed Mar 10 11:38:12  [ERROR] Error making RPC call {"method":"ListVolumes","params":{"includeVirtualVolumes":true},"id":1}: Post https://192.168.1.2/json-rpc/11.3: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by neufeldtech** [comment]
It looks like the docs, code and `.env.example` are out of sync...

In `.env.example` I see 

```bash
export SOLIDFIRE_USER=monitoring_user
export SOLIDFIRE_PASS=monitoring_password
```

In the Readme I see

```bash
SOLIDFIRE_CLIENT_PASSWORD
SOLIDFIRE_CLIENT_USERNAME
```

Also SOLIDFIRE_CLIENT_ENDPOINT may also be falling into this same trap...

I'm guessing that when we did some refactoring with the env variables, config flags, and docs updates this got out of sync....

**Comment by neufeldtech** [comment]
I can reproduce the strange behaviour locally with Docker - still tracking it down fully. I think it's related to the viper config library searching the paths for a config file, and it happens to find `example/config.yaml`, which contains the IP address `https://192.168.1.2/json-rpc/11.3` (the one you mention above).

**Comment by neufeldtech** [comment]
@scaleoutsean so the main issue that you were experiencing regarding the segfault was caused by the way that the variables were passed in the env file.

Apparently this syntax for a docker env file is not valid
```bash
SOLIDFIRE_CLIENT_ENDPOINT="https://10.0.0.80/json-rpc/11.3"
```

If I remove the quotes, then it succeeds properly
```bash
SOLIDFIRE_CLIENT_ENDPOINT=https://10.0.0.80/json-rpc/11.3
```

It was throwing an exception because there was an error constructing the http request that we were failing to catch - I'll fix this up along with the docs.
