### ISSUE TITLE
Errors when multiple Prometehus instances trying to fetch metrics at the same time

### ISSUE THREAD

**Issue by bl0m1** [mjavier2k/solidfire-exporter#67]
Hello!

I need to start of by thanking you for creating this exporter, it is amazing.

We have used it in production for a while now but recently we added an additional prometheus instance to have 2 that scraping the same targets (for redundancy).

Sometime booth prometheus instances trying to fetch data on the same time and the exporter crashes

We are using version ` v0.6.1` of the exporter.

Log output:
```
Thu Jul 29 08:08:49  [INFO ] Found configuration file on /app/config.yaml 
[...]
Thu Jul 29 08:08:49  [INFO ] Booted and listening on 0.0.0.0:9987/metrics
fatal error: concurrent map read and map write

goroutine 8277 [running]:
runtime.throw(0xb24180, 0x21)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00022fa80 sp=0xc00022fa50 pc=0x42e282
runtime.mapaccess1_fast64(0xa3cea0, 0xc00014f5f0, 0x7530, 0x5)
	/usr/local/go/src/runtime/map_fast64.go:21 +0x1a6 fp=0xc00022faa8 sp=0xc00022fa80 pc=0x411196
github.com/mjavier2k/solidfire-exporter/pkg/prom.(*SolidfireCollector).collectVolumeQosHistograms(0xc00014f650, 0xbfd040, 0xc0000a2040, 0xc000406060, 0x0, 0x0)
	/src/pkg/prom/collector.go:814 +0xe86 fp=0xc00022ff18 sp=0xc00022faa8 pc=0x98e876
github.com/mjavier2k/solidfire-exporter/pkg/prom.(*SolidfireCollector).Collect.func8(0xc00003c768, 0x0)
	/src/pkg/prom/collector.go:1278 +0x48 fp=0xc00022ff58 sp=0xc00022ff18 pc=0x999f48
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00014e090, 0xc000175560)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x64 fp=0xc00022ffd0 sp=0xc00022ff58 pc=0x855e64
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00022ffd8 sp=0xc00022ffd0 pc=0x45a741
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66

goroutine 1 [IO wait, 64 minutes]:
internal/poll.runtime_pollWait(0x7f0ef721cf08, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0000f0698, 0x72, 0x0, 0x0, 0xb14218)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000f0680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc0000f0680, 0xc000077c80, 0x6caa44, 0xc0000e6180)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0001a0140, 0x6102624b, 0xc000077c80, 0x4b9016)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0001a0140, 0xc000077cd0, 0x18, 0xc000000180, 0x6c9f5e)
	/usr/local/go/src/net/tcpsock.go:261 +0x47
net/http.(*Server).Serve(0xc0000e60e0, 0xbfa880, 0xc0001a0140, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2896 +0x286
net/http.(*Server).ListenAndServe(0xc0000e60e0, 0xc0000e60e0, 0x7)
	/usr/local/go/src/net/http/server.go:2825 +0xb7
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3080
main.main()
	/src/cmd/solidfire-exporter/main.go:93 +0x66c

goroutine 24 [runnable]:
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc0000aad70, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:513 +0xb49
github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0x7f0ef7225a60, 0xc0001f8140, 0xc000fde000)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/http.go:126 +0x65
net/http.HandlerFunc.ServeHTTP(0xc000182700, 0x7f0ef7225a60, 0xc0001f8140, 0xc000fde000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1(0x7f0ef7225a60, 0xc0001f8140, 0xc000fde000)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:40 +0xbc
net/http.HandlerFunc.ServeHTTP(0xc00014f8c0, 0x7f0ef7225a60, 0xc0001f8140, 0xc000fde000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0xbfab40, 0xc0000e62a0, 0xc000fde000)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:101 +0xda
net/http.HandlerFunc.ServeHTTP(0xc00014fa40, 0xbfab40, 0xc0000e62a0, 0xc000fde000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0x10452e0, 0xbfab40, 0xc0000e62a0, 0xc000fde000)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0000e60e0, 0xbfab40, 0xc0000e62a0, 0xc000fde000)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000155540, 0xbfd040, 0xc0000a3300)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e

goroutine 8330 [semacquire]:
sync.runtime_Semacquire(0xc0010849a0)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc001084998)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
golang.org/x/sync/errgroup.(*Group).Wait(0xc001084990, 0xc001088100, 0xbfd040)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x31
github.com/mjavier2k/solidfire-exporter/pkg/prom.(*SolidfireCollector).Collect(0xc00014f650, 0xc00020a000)
	/src/pkg/prom/collector.go:1260 +0x25a
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:446 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:538 +0xe12

goroutine 8329 [semacquire]:
sync.runtime_Semacquire(0xc001066018)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc001066010)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc001066010, 0xc00020a000, 0xc00020a060)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:463 +0x2b
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:462 +0x5bc

goroutine 113 [select]:
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc0000aad70, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:513 +0xb49
github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0x7f0ef7225a60, 0xc0010c6140, 0xc000fde900)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/http.go:126 +0x65
net/http.HandlerFunc.ServeHTTP(0xc000182700, 0x7f0ef7225a60, 0xc0010c6140, 0xc000fde900)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1(0x7f0ef7225a60, 0xc0010c6140, 0xc000fde900)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:40 +0xbc
net/http.HandlerFunc.ServeHTTP(0xc00014f8c0, 0x7f0ef7225a60, 0xc0010c6140, 0xc000fde900)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0xbfab40, 0xc00030e000, 0xc000fde900)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:101 +0xda
net/http.HandlerFunc.ServeHTTP(0xc00014fa40, 0xbfab40, 0xc00030e000, 0xc000fde900)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0x10452e0, 0xbfab40, 0xc00030e000, 0xc000fde900)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0000e60e0, 0xbfab40, 0xc00030e000, 0xc000fde900)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0000a43c0, 0xbfd040, 0xc000078140)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e

goroutine 8327 [IO wait]:
internal/poll.runtime_pollWait(0x7f0ef721c888, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000236198, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000236180, 0xc000985931, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc000236180, 0xc000985931, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000212030, 0xc000985931, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
net/http.(*connReader).backgroundRead(0xc000985920)
	/usr/local/go/src/net/http/server.go:677 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:673 +0xd4

goroutine 8258 [semacquire]:
sync.runtime_Semacquire(0xc00014e0a0)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc00014e098)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
golang.org/x/sync/errgroup.(*Group).Wait(0xc00014e090, 0xc000175600, 0xbfd040)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x31
github.com/mjavier2k/solidfire-exporter/pkg/prom.(*SolidfireCollector).Collect(0xc00014f650, 0xc000406060)
	/src/pkg/prom/collector.go:1292 +0x75a
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:446 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:538 +0xe12

goroutine 8309 [runnable]:
github.com/mjavier2k/solidfire-exporter/pkg/prom.(*SolidfireCollector).collectVolumeMeta(0xc00014f650, 0xbfd040, 0xc000215140, 0x0, 0x0)
	/src/pkg/prom/collector.go:179 +0x1b8
github.com/mjavier2k/solidfire-exporter/pkg/prom.(*SolidfireCollector).Collect.func2(0xc0009d8f68, 0xc0009d8f48)
	/src/pkg/prom/collector.go:1255 +0x3f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc001084990, 0xc0010880e0)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66

goroutine 8233 [IO wait]:
internal/poll.runtime_pollWait(0x7f0ef721caf8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000284498, 0x72, 0x3300, 0x33dd, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000284480, 0xc00013f500, 0x33dd, 0x33dd, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc000284480, 0xc00013f500, 0x33dd, 0x33dd, 0x203000, 0x4211a5, 0xc0010c4be0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00009e308, 0xc00013f500, 0x33dd, 0x33dd, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
crypto/tls.(*atLeastReader).Read(0xc0010c4be0, 0xc00013f500, 0x33dd, 0x33dd, 0x2000, 0x8, 0xc00018d8a0)
	/usr/local/go/src/crypto/tls/conn.go:780 +0x60
bytes.(*Buffer).ReadFrom(0xc000170258, 0xbef0a0, 0xc0010c4be0, 0x409d65, 0xa59180, 0xae4d80)
	/usr/local/go/src/bytes/buffer.go:204 +0xb4
crypto/tls.(*Conn).readFromUntil(0xc000170000, 0xbef8c0, 0xc00009e308, 0x5, 0xc00009e308, 0xf)
	/usr/local/go/src/crypto/tls/conn.go:802 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000170000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:609 +0x124
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0xc000170000, 0xc000d88000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1255 +0x161
net/http.(*persistConn).Read(0xc0000aca20, 0xc000d88000, 0x1000, 0x1000, 0xc00014ae40, 0xc00018dc20, 0x404cf5)
	/usr/local/go/src/net/http/transport.go:1744 +0x75
bufio.(*Reader).fill(0xc000de9140)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc000de9140, 0x1, 0x0, 0x0, 0x1, 0xc00014a100, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc0000aca20)
	/usr/local/go/src/net/http/transport.go:1897 +0x1d6
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1566 +0xafe

goroutine 8268 [select]:
net/http.(*persistConn).writeLoop(0xc000306120)
	/usr/local/go/src/net/http/transport.go:2196 +0x123
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1567 +0xb23

goroutine 8257 [semacquire]:
sync.runtime_Semacquire(0xc00060a948)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc00060a940)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc00060a940, 0xc000406060, 0xc000406180)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:463 +0x2b
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:462 +0x5bc

goroutine 8267 [IO wait]:
internal/poll.runtime_pollWait(0x7f0ef721cc98, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0000f0198, 0x72, 0x800, 0x825, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000f0180, 0xc0000ba900, 0x825, 0x825, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0000f0180, 0xc0000ba900, 0x825, 0x825, 0x203000, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000212108, 0xc0000ba900, 0x825, 0x825, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
crypto/tls.(*atLeastReader).Read(0xc001088380, 0xc0000ba900, 0x825, 0x825, 0x28, 0x8, 0xc0002e78a0)
	/usr/local/go/src/crypto/tls/conn.go:780 +0x60
bytes.(*Buffer).ReadFrom(0xc00003f758, 0xbef0a0, 0xc001088380, 0x409d65, 0xa59180, 0xae4d80)
	/usr/local/go/src/bytes/buffer.go:204 +0xb4
crypto/tls.(*Conn).readFromUntil(0xc00003f500, 0xbef8c0, 0xc000212108, 0x5, 0xc000212108, 0xf)
	/usr/local/go/src/crypto/tls/conn.go:802 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc00003f500, 0x0, 0x0, 0x3)
	/usr/local/go/src/crypto/tls/conn.go:609 +0x124
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0xc00003f500, 0xc0002de000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1255 +0x161
net/http.(*persistConn).Read(0xc000306120, 0xc0002de000, 0x1000, 0x1000, 0xc0002881e0, 0xc0002e7c20, 0x404cf5)
	/usr/local/go/src/net/http/transport.go:1744 +0x75
bufio.(*Reader).fill(0xc000406720)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc000406720, 0x1, 0x0, 0x0, 0x1, 0xc000288700, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc000306120)
	/usr/local/go/src/net/http/transport.go:1897 +0x1d6
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1566 +0xafe

goroutine 8159 [IO wait]:
internal/poll.runtime_pollWait(0x7f0ef721ce38, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0000f0718, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000f0700, 0xc00019e431, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0000f0700, 0xc00019e431, 0x1, 0x1, 0xc000407680, 0x0, 0xc000064a98)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00009e3e8, 0xc00019e431, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
net/http.(*connReader).backgroundRead(0xc00019e420)
	/usr/local/go/src/net/http/server.go:677 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:673 +0xd4

goroutine 8234 [select]:
net/http.(*persistConn).writeLoop(0xc0000aca20)
	/usr/local/go/src/net/http/transport.go:2196 +0x123
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1567 +0xb23
Thu Jul 29 09:13:48  [INFO ] Found configuration file on /app/config.yaml
[...]
```

**Comment by neufeldtech** [comment]
Thanks for this report @bl0m1 , we'll take a look at this.

**Comment by bl0m1** [comment]
> Thanks for this report @bl0m1 , we'll take a look at this.

Just let me know in case there is anything you need from me/us and I'll do my best helping out

**Comment by neufeldtech** [comment]
@bl0m1  could you please try v0.6.2 and let us know if you still encounter the issue? Thanks.

**Comment by bl0m1** [comment]
> @bl0m1 could you please try [v0.6.2](https://github.com/mjavier2k/solidfire-exporter/releases/tag/v0.6.2) and let us know if you still encounter the issue? Thanks.

Hello again,

Thanks alot for being quick, I'm back from vacation today. I just wanted to check if you have stopped creating docker images. IT looks like v0.6.1 is the latest image available on dockerhub?

**Comment by mjavier2k** [comment]
hey @bl0m1 

try pulling the image from ghcr.io/mjavier2k/solidfire-exporter:v0.6.5. let me know if you get into issues

**Comment by bl0m1** [comment]
> hey @bl0m1
> 
> try pulling the image from ghcr.io/mjavier2k/solidfire-exporter:v0.6.5. let me know if you get into issues

Thanks alot, it worked perfectly :)
